version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.25.1
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.15
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.3.2
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
