name: Prepare Release

on:
  # Manual trigger: useful to force the CI to run in the PR
  workflow_dispatch: {}

  # Update the branch on main
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: Prepare Release (changsets automation)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
